# File    : styles_v10.ini
# Purpose : Generation parameters for different image styles (version 1.0)
# Author  : Martin Rizzo | <martinrizzo@gmail.com>
# Date    : Jan 15, 2025
# Repo    : https://github.com/martin-rizzo/ComfyUI-TinyBreaker
# License : MIT
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#                              ConfyUI-TinyBreaker
# ComfyUI nodes for experimenting with the capabilities of the TinyBreaker model.
#  (TinyBreaker is a hybrid model that combines the strengths of PixArt and SD)
# _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _


# default settings for all styles
base.prompt        = ""
base.negative      = ""
base.start_at_step = 2
base.steps         = 12
base.cfg           = 3.4
base.noise_seed    = 1
base.sampler_name  = "uni_pc"
base.scheduler     = "simple"
refiner.prompt        = ""
refiner.negative      = "(worst quality, low quality:1.8)"
refiner.start_at_step = 6
refiner.steps         = 11
refiner.cfg           = 2.0
refiner.noise_seed    = 1
refiner.sampler_name  = "deis"
refiner.scheduler     = "ddim_uniform"


[PHOTO]
# realistic images with photographic details
base.prompt   = "A detailed iPhone photo{. prompt}"
base.negative = "macrophoto, bokeh, out of focus, draw{. prompt}"
refiner.negative = "(draw, worst quality, low quality:1.8)"


[DARKFAN80]
# dark fantasy, cinematic 80s style with VHS aesthetics and dramatic lighting.
base.prompt        = "{prompt .}bokeh, (80's dark fantasy in VHS, blurry tv captured:1.1)"
base.negative      = "small toy, painting{, prompt}"
base.sampler_name  = "dpmpp_2m_sde"
refiner.start_at_step = 7
refiner.steps         = 12


[PIXELART]
# pixel art style with retro aesthetics and vibrant, blocky details
base.prompt   = "A pixel-art image{. prompt}. low-res, blocky, pixel art style, 8-bit graphics"
base.negative = "blurry, noisy, highly detailed, ultra textured, photo, realistic, macrophoto{, prompt}"
refiner.prompt        = "pixel-art, low-res, blocky"
refiner.negative      = "soft"
refiner.cfg           = 8.0
refiner.start_at_step = 6
refiner.steps         = 8


[INK]
# ink-style illustrations with bold outlines and hand-painted details
base.prompt   = "Cute pencil illustration{. prompt}. Outlined minimalist with solid colors."
base.negative = "blurry{, prompt}"
refiner.negative      = "(worst quality, low quality:2.0)"
refiner.start_at_step = 6
refiner.steps         = 8
refiner.cfg           = 1.5


[CUTETOY]
base.prompt   = "Isometric cure render, toy{. prompt}"
base.negative = "sharp{, prompt}"
refiner.prompt        = "isometric, low-poly."
refiner.start_at_step = 6
refiner.steps         = 11

[none]

[CUSTOM.1]
# reserved for user-defined style

[CUSTOM.2]
# reserved for user-defined style

